import java.util.*;
class ternary
{
    public static void main(String[] a)
    {
int day;
Scanner sc=new Scanner(System.in);
System.out.println("enter the day");
day=sc.nextInt();
switch(day)
{
    case 1:
        System.out.println("wake up at 6am");
        break;
        case 2:
            System.out.println("wake up at 4am");
            break;
            default:
            System.out.println("thongo");
}
        
}
        
    }
